include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - avoid_print
    - require_trailing_commas
    - prefer_single_quotes
    - cascade_invocations
    - always_use_package_imports
